#!/usr/bin/expect -f

set timeout -1
spawn /Users/garthbjerk/automation/run_fab_update
expect "What should the site.domain setting be?"
send -- "garth.local:8000\r"
expect "Set a new password for all accounts: "
send -- "bogus\r"
expect eof
